In [133]:
#Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from numpy import nan
import matplotlib.pyplot as plt
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils.vis_utils import plot_model
from IPython.display import Image 

In [27]:
from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelBinarizer
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [28]:
import tensorflow as tf

In [29]:
path = './data_documentation/'
ranking_data = 'filtered_ranking_4_year_df.csv'

In [77]:
ranking_df = pd.read_csv(path + ranking_data, index_col = 0)

In [78]:
ranking_df

Rank  CONTROL  LOCALE  LOCALE2  MENONLY  WOMENONLY  ADM_RATE  \
0     456        1    12.0      0.0      0.0        0.0    0.9211   
1     475        1    12.0      0.0      0.0        0.0    0.8087   
2     252        1    12.0      0.0      0.0        0.0    0.5906   
3     166        1    13.0      0.0      0.0        0.0    0.7543   
4     463        2    12.0      0.0      0.0        0.0    0.5666   
..    ...      ...     ...      ...      ...        ...       ...   
635   118        1    13.0      0.0      0.0        0.0    0.5798   
636   577        2    41.0      0.0      0.0        0.0    0.6704   
637   277        1    13.0      0.0      0.0        0.0    0.7679   
638   519        1    21.0      0.0      0.0        0.0    0.6492   
639   505        1    31.0      0.0      0.0        0.0    0.8094   

     ADM_RATE_ALL  SATVRMID  SATMTMID  ...  Alumni Salary  Acceptance Rate  \
0          0.9211     555.0     555.0  ...        87200.0             92.0   
1          0.8087     630.0     565.0  ...       103900.0             81.0   
2          0.5906     590.0     580.0  ...        97400.0             53.0   
3          0.7543     615.0     615.0  ...       104500.0             84.0   
4          0.5666     570.0     560.0  ...        88300.0             62.0   
..            ...       ...       ...  ...            ...              ...   
635        0.5798     635.0     660.0  ...       110000.0             57.0   
636        0.6704     665.0     645.0  ...            0.0             63.0   
637        0.7679     675.0     645.0  ...        86500.0             69.0   
638        0.6492     580.0     555.0  ...        80000.0             64.0   
639        0.8094     588.0     540.0  ...        85600.0             78.0   

     SAT Lower  SAT Upper  ACT Lower  ACT Upper  10%_cut  5%_cut  20%_cut  \
0        990.0     1370.0       21.0       28.0        7      14        3   
1       1080.0     1330.0       25.0       31.0        7      14        3   
2       1050.0     1280.0       23.0       32.0        3       7        1   
3       1130.0     1310.0       24.0       30.0        2       4        1   
4       1030.0     1260.0       23.0       29.0        7      14        3   
..         ...        ...        ...        ...      ...     ...      ...   
635     1150.0     1380.0       25.0       31.0        1       3        0   
636     1190.0     1350.0       23.0       32.0        8      17        4   
637     1190.0     1380.0       25.0       30.0        4       8        2   
638     1060.0     1210.0       21.0       25.0        7      15        3   
639      910.0     1130.0       20.0       25.0        7      15        3   

     50%_cut  
0          1  
1          1  
2          0  
3          0  
4          1  
..       ...  
635        0  
636        1  
637        0  
638        1  
639        1  

[640 rows x 197 columns]

In [79]:
y_data = ranking_df['20%_cut']

In [80]:
y = y_data.to_numpy()

In [81]:
ranking_df = ranking_df.drop(columns = ['Rank', '5%_cut', '10%_cut', '20%_cut', '50%_cut'])

In [82]:
ranking_df

CONTROL  LOCALE  LOCALE2  MENONLY  WOMENONLY  ADM_RATE  ADM_RATE_ALL  \
0          1    12.0      0.0      0.0        0.0    0.9211        0.9211   
1          1    12.0      0.0      0.0        0.0    0.8087        0.8087   
2          1    12.0      0.0      0.0        0.0    0.5906        0.5906   
3          1    13.0      0.0      0.0        0.0    0.7543        0.7543   
4          2    12.0      0.0      0.0        0.0    0.5666        0.5666   
..       ...     ...      ...      ...        ...       ...           ...   
635        1    13.0      0.0      0.0        0.0    0.5798        0.5798   
636        2    41.0      0.0      0.0        0.0    0.6704        0.6704   
637        1    13.0      0.0      0.0        0.0    0.7679        0.7679   
638        1    21.0      0.0      0.0        0.0    0.6492        0.6492   
639        1    31.0      0.0      0.0        0.0    0.8094        0.8094   

     SATVRMID  SATMTMID  SATWRMID  ...  Student Population  Net Price  \
0       555.0     555.0       0.0  ...               20902    17535.0   
1       630.0     565.0       0.0  ...                9101    19986.0   
2       590.0     580.0     540.0  ...               38563    21973.0   
3       615.0     615.0     570.0  ...               29776    23416.0   
4       570.0     560.0       0.0  ...                1325    22853.0   
..        ...       ...       ...  ...                 ...        ...   
635     635.0     660.0     570.0  ...               42699    13746.0   
636     665.0     645.0       0.0  ...                 386    20605.0   
637     675.0     645.0     620.0  ...                 885    10248.0   
638     580.0     555.0     520.0  ...               15317    15376.0   
639     588.0     540.0       0.0  ...               20811     9854.0   

     Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
0               9254.0              36800        87200.0             92.0   
1               9587.0              36881       103900.0             81.0   
2              16494.0              46744        97400.0             53.0   
3               9030.0              49954       104500.0             84.0   
4              26594.0              52414        88300.0             62.0   
..                 ...                ...            ...              ...   
635            10703.0              41614       110000.0             57.0   
636            31845.0              65456            0.0             63.0   
637             9341.0              43678        86500.0             69.0   
638             4726.0              39434        80000.0             64.0   
639             5483.0              28094        85600.0             78.0   

     SAT Lower  SAT Upper  ACT Lower  ACT Upper  
0        990.0     1370.0       21.0       28.0  
1       1080.0     1330.0       25.0       31.0  
2       1050.0     1280.0       23.0       32.0  
3       1130.0     1310.0       24.0       30.0  
4       1030.0     1260.0       23.0       29.0  
..         ...        ...        ...        ...  
635     1150.0     1380.0       25.0       31.0  
636     1190.0     1350.0       23.0       32.0  
637     1190.0     1380.0       25.0       30.0  
638     1060.0     1210.0       21.0       25.0  
639      910.0     1130.0       20.0       25.0  

[640 rows x 192 columns]

In [83]:
# Splitting the data into training and test test
X = ranking_df.iloc[:,1:196].values


In [84]:
X

array([[  12.,    0.,    0., ..., 1370.,   21.,   28.],
       [  12.,    0.,    0., ..., 1330.,   25.,   31.],
       [  12.,    0.,    0., ..., 1280.,   23.,   32.],
       ...,
       [  13.,    0.,    0., ..., 1380.,   25.,   30.],
       [  21.,    0.,    0., ..., 1210.,   21.,   25.],
       [  31.,    0.,    0., ..., 1130.,   20.,   25.]])

In [85]:
len(X[0])

191

In [86]:
y

array([3, 3, 1, 1, 3, 1, 4, 4, 4, 4, 1, 1, 3, 4, 2, 2, 2, 3, 3, 2, 0, 1,
       0, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0,
       0, 4, 3, 2, 0, 2, 4, 0, 1, 0, 0, 1, 0, 2, 1, 1, 3, 1, 2, 0, 2, 3,
       4, 0, 1, 3, 3, 4, 1, 0, 0, 1, 1, 4, 4, 2, 4, 0, 0, 1, 4, 1, 2, 0,
       0, 0, 1, 0, 2, 0, 0, 2, 4, 1, 3, 2, 2, 3, 2, 2, 2, 3, 1, 0, 0, 0,
       3, 3, 1, 1, 3, 3, 4, 3, 3, 2, 0, 0, 2, 4, 3, 0, 3, 4, 4, 3, 2, 4,
       3, 4, 3, 2, 4, 2, 0, 1, 3, 2, 4, 0, 1, 4, 1, 2, 2, 3, 1, 4, 4, 3,
       4, 0, 4, 4, 4, 0, 4, 3, 1, 0, 2, 2, 3, 2, 4, 4, 4, 0, 0, 0, 2, 1,
       3, 2, 3, 4, 3, 3, 2, 1, 0, 1, 1, 2, 3, 3, 3, 1, 2, 4, 4, 3, 3, 1,
       4, 4, 2, 3, 4, 4, 2, 4, 4, 1, 3, 3, 4, 4, 4, 0, 4, 0, 0, 0, 3, 3,
       3, 4, 0, 1, 1, 0, 2, 1, 1, 2, 2, 3, 0, 2, 0, 0, 0, 0, 1, 1, 2, 2,
       0, 0, 3, 1, 4, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 3, 4,
       4, 2, 4, 2, 3, 1, 1, 3, 0, 1, 2, 4, 4, 4, 2, 0, 2, 1, 3, 0, 4, 0,
       3, 2, 3, 1, 4, 1, 3, 0, 3, 1, 4, 2, 3, 3, 3,

In [87]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [88]:
y1

array([3, 3, 1, 1, 3, 1, 4, 4, 4, 4, 1, 1, 3, 4, 2, 2, 2, 3, 3, 2, 0, 1,
       0, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0,
       0, 4, 3, 2, 0, 2, 4, 0, 1, 0, 0, 1, 0, 2, 1, 1, 3, 1, 2, 0, 2, 3,
       4, 0, 1, 3, 3, 4, 1, 0, 0, 1, 1, 4, 4, 2, 4, 0, 0, 1, 4, 1, 2, 0,
       0, 0, 1, 0, 2, 0, 0, 2, 4, 1, 3, 2, 2, 3, 2, 2, 2, 3, 1, 0, 0, 0,
       3, 3, 1, 1, 3, 3, 4, 3, 3, 2, 0, 0, 2, 4, 3, 0, 3, 4, 4, 3, 2, 4,
       3, 4, 3, 2, 4, 2, 0, 1, 3, 2, 4, 0, 1, 4, 1, 2, 2, 3, 1, 4, 4, 3,
       4, 0, 4, 4, 4, 0, 4, 3, 1, 0, 2, 2, 3, 2, 4, 4, 4, 0, 0, 0, 2, 1,
       3, 2, 3, 4, 3, 3, 2, 1, 0, 1, 1, 2, 3, 3, 3, 1, 2, 4, 4, 3, 3, 1,
       4, 4, 2, 3, 4, 4, 2, 4, 4, 1, 3, 3, 4, 4, 4, 0, 4, 0, 0, 0, 3, 3,
       3, 4, 0, 1, 1, 0, 2, 1, 1, 2, 2, 3, 0, 2, 0, 0, 0, 0, 1, 1, 2, 2,
       0, 0, 3, 1, 4, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 3, 4,
       4, 2, 4, 2, 3, 1, 1, 3, 0, 1, 2, 4, 4, 4, 2, 0, 2, 1, 3, 0, 4, 0,
       3, 2, 3, 1, 4, 1, 3, 0, 3, 1, 4, 2, 3, 3, 3,

In [89]:
Y = pd.get_dummies(y1).values

In [90]:
Y

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [92]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

In [120]:
model = Sequential()
model.add(Dense(1000,input_dim = 191,activation='tanh', name = 'layer_1'))
#model.add(Dense(128,input_shape=(191,),activation='tanh', name = 'layer_1'))
#model.add(Dense(1000,activation='tanh', name = 'layer_2'))
#model.add(Dense(400,activation='tanh', name = 'layer_3'))
#model.add(Dense(400,activation='tanh', name = 'layer_4'))
#model.add(Dense(400,activation='tanh', name = 'layer_5'))
#model.add(Dense(400,activation='tanh', name = 'layer_6'))
model.add(Dense(5,activation='softmax'))

model.compile(Adam(lr=0.001),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer_1 (Dense)              (None, 1000)              192000    
_________________________________________________________________
dense_30 (Dense)             (None, 5)                 5005      
Total params: 197,005
Trainable params: 197,005
Non-trainable params: 0
_________________________________________________________________


In [121]:
#fitting the model and predicting 
model.fit(X_train,y_train,epochs=1000)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.7998 - accuracy: 0.2441
Epoch 2/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.4891 - accuracy: 0.3535
Epoch 3/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.3866 - accuracy: 0.4062
Epoch 4/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.3215 - accuracy: 0.4277
Epoch 5/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.3062 - accuracy: 0.4414
Epoch 6/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.2495 - accuracy: 0.4805
Epoch 7/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.2188 - accuracy: 0.5000
Epoch 8/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.2793 - accuracy: 0.4551
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 1.2427 - accuracy: 0.4707
Epoch 10/1000
16/16 [==============================] - 0s 1ms/step - loss: 1.1849 - accuracy: 0.5098

16/16 [==============================] - 0s 2ms/step - loss: 0.6365 - accuracy: 0.7930
Epoch 83/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6451 - accuracy: 0.7695
Epoch 84/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6614 - accuracy: 0.7539
Epoch 85/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6427 - accuracy: 0.7793
Epoch 86/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6329 - accuracy: 0.7852
Epoch 87/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6386 - accuracy: 0.7832
Epoch 88/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.6369 - accuracy: 0.7871
Epoch 89/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6445 - accuracy: 0.7480
Epoch 90/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6385 - accuracy: 0.7832
Epoch 91/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.6240 - accuracy: 0.7930
Epoc

16/16 [==============================] - 0s 1ms/step - loss: 0.4989 - accuracy: 0.8457
Epoch 163/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4988 - accuracy: 0.8340
Epoch 164/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.4941 - accuracy: 0.8262
Epoch 165/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4916 - accuracy: 0.8398
Epoch 166/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4998 - accuracy: 0.8457
Epoch 167/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.5135 - accuracy: 0.8184
Epoch 168/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4859 - accuracy: 0.8457
Epoch 169/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4755 - accuracy: 0.8555
Epoch 170/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4706 - accuracy: 0.8496
Epoch 171/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4831 - accuracy: 0.

16/16 [==============================] - 0s 2ms/step - loss: 0.4155 - accuracy: 0.8730
Epoch 243/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4080 - accuracy: 0.8789
Epoch 244/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4147 - accuracy: 0.8730
Epoch 245/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.4145 - accuracy: 0.8750
Epoch 246/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.4248 - accuracy: 0.8594
Epoch 247/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.3957 - accuracy: 0.8809
Epoch 248/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8613
Epoch 249/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.4151 - accuracy: 0.8594
Epoch 250/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3880 - accuracy: 0.8926
Epoch 251/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3991 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.3443 - accuracy: 0.8965
Epoch 323/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.9023
Epoch 324/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.9141
Epoch 325/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3678 - accuracy: 0.8770
Epoch 326/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8945
Epoch 327/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3595 - accuracy: 0.8926
Epoch 328/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.9121
Epoch 329/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.9043
Epoch 330/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.3583 - accuracy: 0.9023
Epoch 331/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3267 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8965
Epoch 403/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.9082
Epoch 404/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.9199
Epoch 405/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.9160
Epoch 406/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3372 - accuracy: 0.8965
Epoch 407/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.9082
Epoch 408/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.3050 - accuracy: 0.9043
Epoch 409/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2998 - accuracy: 0.9102
Epoch 410/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.9180
Epoch 411/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2848 - accuracy: 0.

16/16 [==============================] - 0s 2ms/step - loss: 0.2659 - accuracy: 0.9375
Epoch 483/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2525 - accuracy: 0.9395
Epoch 484/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2651 - accuracy: 0.9297
Epoch 485/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2613 - accuracy: 0.9297
Epoch 486/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2714 - accuracy: 0.9277
Epoch 487/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2540 - accuracy: 0.9434
Epoch 488/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2822 - accuracy: 0.9180
Epoch 489/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2768 - accuracy: 0.9141
Epoch 490/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2912 - accuracy: 0.9141
Epoch 491/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2688 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.2461 - accuracy: 0.9434
Epoch 563/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2434 - accuracy: 0.9434
Epoch 564/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2352 - accuracy: 0.9414
Epoch 565/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2334 - accuracy: 0.9434
Epoch 566/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2453 - accuracy: 0.9316
Epoch 567/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2416 - accuracy: 0.9355
Epoch 568/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2331 - accuracy: 0.9414
Epoch 569/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2408 - accuracy: 0.9492
Epoch 570/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2350 - accuracy: 0.9414
Epoch 571/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2434 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.2159 - accuracy: 0.9434
Epoch 643/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2075 - accuracy: 0.9590
Epoch 644/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2286 - accuracy: 0.9395
Epoch 645/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2092 - accuracy: 0.9512
Epoch 646/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2031 - accuracy: 0.9551
Epoch 647/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2090 - accuracy: 0.9492
Epoch 648/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2229 - accuracy: 0.9395
Epoch 649/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2306 - accuracy: 0.9355
Epoch 650/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2160 - accuracy: 0.9453
Epoch 651/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2251 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.1959 - accuracy: 0.9492
Epoch 723/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1911 - accuracy: 0.9551
Epoch 724/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1840 - accuracy: 0.9629
Epoch 725/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1864 - accuracy: 0.9688
Epoch 726/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1903 - accuracy: 0.9590
Epoch 727/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2063 - accuracy: 0.9512
Epoch 728/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2068 - accuracy: 0.9434
Epoch 729/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2093 - accuracy: 0.9551
Epoch 730/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.2201 - accuracy: 0.9297
Epoch 731/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1923 - accuracy: 0.

16/16 [==============================] - 0s 2ms/step - loss: 0.1819 - accuracy: 0.9531
Epoch 803/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1747 - accuracy: 0.9648
Epoch 804/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1794 - accuracy: 0.9473
Epoch 805/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1771 - accuracy: 0.9492
Epoch 806/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1821 - accuracy: 0.9551
Epoch 807/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1838 - accuracy: 0.9648
Epoch 808/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1842 - accuracy: 0.9590
Epoch 809/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1898 - accuracy: 0.9512
Epoch 810/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.2046 - accuracy: 0.9414
Epoch 811/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1744 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.1665 - accuracy: 0.9492
Epoch 883/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1643 - accuracy: 0.9609
Epoch 884/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1572 - accuracy: 0.9668
Epoch 885/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1592 - accuracy: 0.9648
Epoch 886/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1708 - accuracy: 0.9570
Epoch 887/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1678 - accuracy: 0.9609
Epoch 888/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1640 - accuracy: 0.9629
Epoch 889/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1586 - accuracy: 0.9707
Epoch 890/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1616 - accuracy: 0.9648
Epoch 891/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1612 - accuracy: 0.

16/16 [==============================] - 0s 1ms/step - loss: 0.1532 - accuracy: 0.9590
Epoch 963/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1514 - accuracy: 0.9648
Epoch 964/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1453 - accuracy: 0.9766
Epoch 965/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1566 - accuracy: 0.9668
Epoch 966/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1540 - accuracy: 0.9688
Epoch 967/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1593 - accuracy: 0.9707
Epoch 968/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1631 - accuracy: 0.9570
Epoch 969/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1466 - accuracy: 0.9648
Epoch 970/1000
16/16 [==============================] - 0s 1ms/step - loss: 0.1509 - accuracy: 0.9746
Epoch 971/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.1503 - accuracy: 0.

In [122]:

#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))


              precision    recall  f1-score   support

           0       0.81      0.65      0.72        26
           1       0.48      0.45      0.47        22
           2       0.30      0.38      0.34        26
           3       0.29      0.42      0.34        19
           4       0.80      0.57      0.67        35

    accuracy                           0.51       128
   macro avg       0.53      0.50      0.51       128
weighted avg       0.57      0.51      0.53       128

[[17  5  3  1  0]
 [ 2 10  8  2  0]
 [ 2  4 10  8  2]
 [ 0  1  7  8  3]
 [ 0  1  5  9 20]]


In [123]:
# Summary of neural network
model.summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer_1 (Dense)              (None, 1000)              192000    
_________________________________________________________________
dense_30 (Dense)             (None, 5)                 5005      
Total params: 197,005
Trainable params: 197,005
Non-trainable params: 0
_________________________________________________________________


In [142]:
plot_model(model, show_shapes=True, show_layer_names=True, to_file='model.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [144]:
tf.keras.utils.plot_model(
    model, to_file='model.png', show_shapes=False, show_layer_names=True,
    rankdir='TB', expand_nested=False, dpi=96
)


('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')
